### ISSUE TITLE
Error while adding 1.2.5 package

### ISSUE THREAD

**Issue by aakrandan** [migueldeicaza/SkiaKit#32]
https://github.com/migueldeicaza/SkiaKit/releases/download/1.2.4/SkiaSharp.xcframework.zip

The URL is not updated in package.swift.

Should we change it to ?
https://github.com/migueldeicaza/SkiaKit/releases/download/1.2.5/SkiaSharp.xcframework.zip

**Comment by migueldeicaza** [comment]
I think this is fixed
