### ISSUE TITLE
download-payload.sh was deleted but make download-payload still invokes it.

### ISSUE THREAD

**Issue by farzonl** [migueldeicaza/SkiaKit#38]
commit: a156496430b080363dcd598246733ccd6b751118 deleted download-payload.sh. I'm assuming the intent is to move to swift package manager entirely.

https://github.com/migueldeicaza/SkiaKit/commit/a156496430b080363dcd598246733ccd6b751118#diff-c1c5e6d88fda70033edb0b3a2df69ed5663d226e5cd2990cb87c8b80f1de4b78

I have a hybrid c++\swift app I want to upgrade to 1.2.5, but I don't have the energy to update my build system to figure out how to make swift package manager and cmake play nice. What do you suppose it would take if I wanted to support my own `download-payload.sh` script?

**Comment by migueldeicaza** [comment]
There is a `make-xcframework.sh` that is now used for MacOS, only the Linux payload downloaded remains.

I think the Makefile targets are old and need to be removed.

You could always recover the file for your own use I guess.
