### ISSUE TITLE
Is this project still maintained? Sample and steps for adding package do not work.

### ISSUE THREAD

**Issue by msivers** [migueldeicaza/SkiaKit#39]
I was looking to port a project I built in Xamarin Forms / MAUI which uses SkiaSharp to Swift but the sample project doesn't build and I can't even get a default SwiftUI project to build following steps provided or by using the swift package manager.

Before I invest anymore time in looking at porting I just want to check if this project is maintained and if so would it be possible for updated steps or sample app be provided?

Many thanks in advance.

**Comment by migueldeicaza** [comment]
I work on it on my spare time, and I was going to upgrade to the new Skia API, but I am waiting for Matthew to release the 3.0 bindings.

Feel free to send PRs.
